services:
  api:
    build:
      context: ./api
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      - GOOGLE_CLOUD_PROJECT_ID=${GOOGLE_CLOUD_PROJECT_ID}
      - FIRESTORE_DATABASE_ID=${FIRESTORE_DATABASE_ID}
      - FIRESTORE_COLLECTION_PREFIX=${FIRESTORE_COLLECTION_PREFIX}
      - QUARKUS_PROFILE=prod
      - QUARKUS_HTTP_PORT=8080
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN:-}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET:-}
    ports:
      - "8080:8080"

  front:
    build:
      context: ./front
      args:
        - API_URL=http://localhost:8080
    ports:
      - "80:3000"
    environment:
      - API_URL=http://localhost:8080
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_PUBLIC_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    depends_on:
      - api
    x-google-cloudrun:
      ingress-container: true
