# Configuration Google Cloud
quarkus.google.cloud.project-id=${GOOGLE_CLOUD_PROJECT_ID}

# Instance de la base de données Firestore ((default) par défaut)
# Modifier pour basculer entre thezaurus-dev et thezaurus-prod
quarkus.google.cloud.firestore.database-id=${FIRESTORE_DATABASE_ID:thezaurus-dev}
# Configuration des identifiants (Compte de Service)
quarkus.google.cloud.credentials.type=service-account
quarkus.google.cloud.credentials.location=${GOOGLE_APPLICATION_CREDENTIALS}

# Emulator (utilisé pour le développement local via docker-compose)
# quarkus.google.cloud.firestore.emulator.host=localhost:8080
