/**
 * @generated
 * Code generated by `npm run generate:api` from api/openapi.json — DO NOT EDIT DIRECTLY.
 *
 * Ce fichier est généré automatiquement. Toute modification manuelle sera écrasée.
 * @readonly
 */

// Alias lisibles sur les schémas générés (`components["schemas"]["X"]` est exact mais verbeux).

import type { components } from "./schema";

type Schemas = components["schemas"];

export type BackendBlogPost = Schemas["BlogPost"];
export type BackendBlogPostStatus = Schemas["BlogPostStatus"];
export type BackendCityCount = Schemas["CityCount"];
export type BackendConference = Schemas["Conference"];
export type BackendConferencePeriod = Schemas["ConferencePeriod"];
export type BackendConferenceReach = Schemas["ConferenceReach"];
export type BackendConferenceType = Schemas["ConferenceType"];
export type BackendCurrentUserView = Schemas["CurrentUserView"];
export type BackendDatePrecision = Schemas["DatePrecision"];
export type BackendEvent = Schemas["Event"];
export type BackendEventsDashboard = Schemas["EventsDashboard"];
export type BackendEventsTotals = Schemas["EventsTotals"];
export type BackendEventTypeSummary = Schemas["EventTypeSummary"];
export type BackendLocation = Schemas["Location"];
export type BackendMessageTemplateDefinition = Schemas["MessageTemplateDefinition"];
export type BackendMonthLabel = Schemas["MonthLabel"];
export type BackendMonthlyActivity = Schemas["MonthlyActivity"];
export type BackendNotificationPreferences = Schemas["NotificationPreferences"];
export type BackendOffice = Schemas["Office"];
export type BackendOfficePreference = Schemas["OfficePreference"];
export type BackendPreviewContext = Schemas["PreviewContext"];
export type BackendProfileView = Schemas["ProfileView"];
export type BackendReminderTemplatePreview = Schemas["ReminderTemplatePreview"];
export type BackendReminderTemplatePreviewRequest = Schemas["ReminderTemplatePreviewRequest"];
export type BackendReminderTemplateUpdate = Schemas["ReminderTemplateUpdate"];
export type BackendReminderTemplateView = Schemas["ReminderTemplateView"];
export type BackendRole = Schemas["Role"];
export type BackendRolesUpdateRequest = Schemas["RolesUpdateRequest"];
export type BackendTalk = Schemas["Talk"];
export type BackendTalkFormat = Schemas["TalkFormat"];
export type BackendTalkReviewRequest = Schemas["TalkReviewRequest"];
export type BackendTalkReviewResponse = Schemas["TalkReviewResponse"];
export type BackendTalkStatus = Schemas["TalkStatus"];
export type BackendTemplateContextOption = Schemas["TemplateContextOption"];
export type BackendTemplateContextPage = Schemas["TemplateContextPage"];
export type BackendTemplateLink = Schemas["TemplateLink"];
export type BackendTemplateToken = Schemas["TemplateToken"];
export type BackendUser = Schemas["User"];
export type BackendUserAdminView = Schemas["UserAdminView"];
export type BackendUserSummary = Schemas["UserSummary"];
export type BackendVisibility = Schemas["Visibility"];
